// <auto-generated />
using System;
using DesafioDev.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioDev.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221023200249_MigrationInicial")]
    partial class MigrationInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioDev.Domain.Entitys.Fornecedor", b =>
                {
                    b.Property<int>("for_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("for_cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("for_nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("for_codigo");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("DesafioDev.Domain.Entitys.Produto", b =>
                {
                    b.Property<int>("pro_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("for_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("pro_datafabricacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("pro_datavalidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("pro_nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("pro_situacao")
                        .HasColumnType("bit");

                    b.HasKey("pro_codigo");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
